#title: Count unique itemColor values
#tags: color

PREFIX soch: <http://kulturarvsdata.se/ksamsok#>

SELECT ?color (COUNT(?color) AS ?count) WHERE {
  ?item soch:itemColor ?color .
}
GROUP BY ?color
ORDER BY DESC(?count)
