#title: Get all References: Kungshögarna
#tags: monuments,fmis,references

PREFIX soch: <http://kulturarvsdata.se/ksamsok#>
PREFIX fmis: <http://kulturarvsdata.se/raa/fmi/>

SELECT ?refs WHERE {
  fmis:10028201230001 soch:itemDescription ?description_node .
  ?description_node soch:type "Referenser" .
  ?description_node soch:desc ?refs .
}
