#title: Get Items with an Image Media Type
#tags: mediatype

PREFIX soch: <http://kulturarvsdata.se/ksamsok#>

SELECT ?item WHERE {
  ?item soch:image ?image .
  ?image soch:mediaType ?mediaType . 
  FILTER REGEX(STR(?mediaType), "image")
}
