#title: Media License Usage
#tags: license

PREFIX soch: <http://kulturarvsdata.se/ksamsok#>

SELECT ?license (COUNT(?license) AS ?count) WHERE {
  ?item soch:mediaLicenseUrl ?license
}
GROUP BY ?license
