#title: Get Items with Images from Uppsala Museum without License
#tags: license

PREFIX soch: <http://kulturarvsdata.se/ksamsok#>

SELECT DISTINCT ?item WHERE {
  ?item soch:serviceOrganization> "upmu" .
  ?item soch:image ?image .
  FILTER NOT EXISTS { ?image soch:mediaLicenseUrl ?license }
}
