#title: Summarize usage of Media Types
#tags: mediatype

PREFIX soch: <http://kulturarvsdata.se/ksamsok#>

SELECT ?mediaType (COUNT(?mediaType) AS ?count) WHERE {
  ?item soch:mediaType ?mediaType .
}
GROUP BY ?mediaType
ORDER BY DESC(?count)
